export const EListWalletAction = {
  GET_LIST_WALLET: 'GET_LIST_WALLET',
  GET_LIST_WALLET_REQUEST: 'GET_LIST_WALLET_REQUEST',
  GET_LIST_WALLET_SUCCESS: 'GET_LIST_WALLET_SUCCESS',
  GET_LIST_WALLET_FAILED: 'GET_LIST_WALLET_FAILED',
};
