export const EConfigAction = {
  GET_CONFIG: 'GET_CONFIG',
  GET_CONFIG_REQUEST: 'GET_CONFIG_REQUEST',
  GET_CONFIG_SUCCESS: 'GET_CONFIG_SUCCESS',
  GET_CONFIG_FAILED: 'GET_CONFIG_FAILED',

  UPDATE_CONFIG: 'UPDATE_CONFIG',
  UPDATE_CONFIG_REQUEST: 'UPDATE_CONFIG_REQUEST',
  UPDATE_CONFIG_SUCCESS: 'UPDATE_CONFIG_SUCCESS',
  UPDATE_CONFIG_FAILED: 'UPDATE_CONFIG_FAILED',
};
