export const EHistoryRotationAction = {
  GET_LIST_HISTORY_ROTATION: 'GET_LIST_HISTORY_ROTATION',
  GET_LIST_HISTORY_ROTATION_REQUEST: 'GET_LIST_HISTORY_ROTATION_REQUEST',
  GET_LIST_HISTORY_ROTATION_SUCCESS: 'GET_LIST_HISTORY_ROTATION_SUCCESS',
  GET_LIST_HISTORY_ROTATION_FAILED: 'GET_LIST_HISTORY_ROTATION_FAILED',
};
