export const EListRotationAction = {
  GET_LIST_ROTATION: 'GET_LIST_ROTATION',
  GET_LIST_ROTATION_REQUEST: 'GET_LIST_ROTATION_REQUEST',
  GET_LIST_ROTATION_SUCCESS: 'GET_LIST_ROTATION_SUCCESS',
  GET_LIST_ROTATION_FAILED: 'GET_LIST_ROTATION_FAILED',

  UPDATE_ROTATION: 'UPDATE_ROTATION',
  UPDATE_ROTATION_REQUEST: 'UPDATE_ROTATION_REQUEST',
  UPDATE_ROTATION_SUCCESS: 'UPDATE_ROTATION_SUCCESS',
  UPDATE_ROTATION_FAILED: 'UPDATE_ROTATION_FAILED',
};
